databases:
  - name: Best-Render
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Best-Render
    env: python
    repo: https://github.com/The-Tepthon/Userbot
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m Tepthon
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DATABASE_URL
        fromDatabase:
          name: Best-Render
          property: connectionString  
  
